// <auto-generated />
using AzureDotNetMVCapp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AzureDotNetMVCapp.Migrations
{
    [DbContext(typeof(azureappdbcontext))]
    [Migration("20240611120138_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AzureDotNetMVCapp.Models.Sunscreen", b =>
                {
                    b.Property<int>("SunscreenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SunscreenId"));

                    b.Property<string>("OxyBenzenoneFree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PARating")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SunscreenName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SunscreenId");

                    b.ToTable("Sunscreens");

                    b.HasData(
                        new
                        {
                            SunscreenId = 1,
                            OxyBenzenoneFree = "NO",
                            PARating = "PA ++++",
                            SPF = "50",
                            SunscreenName = "Minimalist"
                        },
                        new
                        {
                            SunscreenId = 2,
                            OxyBenzenoneFree = "YES",
                            PARating = "PA ++++",
                            SPF = "60",
                            SunscreenName = "Derama Co"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
